---
title: "Shiny Dashboard"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
runtime: shiny
---

```{r setup, include=FALSE}
library(flexdashboard)
library(tidyverse)
library(viridis)
library(p8105.datasets)
library(plotly)
```

```{r, data_import}
data("nyc_airbnb")

nyc_airbnb = 
  nyc_airbnb %>% 
  mutate(stars = review_scores_location / 2) %>%
  select(
    borough = neighbourhood_group, neighbourhood, stars, price, room_type,
    lat, long) %>%
  drop_na(stars)
```


Column {.sidebar}
-----------------------------------------------------------------------

```{r}
borough_choice = 
  nyc_airbnb %>% 
  distinct(borough) %>% 
  pull()

selectInput(
  "borough_choice", 
  label = h3("Select Borough"), #h3: header 3
  choices = borough_choice, 
  selected = "Manhattan")

min_price =
  nyc_airbnb %>% 
  distinct(price) %>% 
  min()
max_price =
  nyc_airbnb %>% 
  distinct(price) %>% 
  max()

sliderInput(
  "price_choice", 
  label = h3("Price Range"), 
  min = min_price, 
  max = 1000, 
  value = c(100, 500))

room_choice = 
  nyc_airbnb %>% 
  distinct(room_type) %>% 
  pull()

# radioButtons widget
radioButtons(
  "room_choice", 
  label = h3("Room Type"),
  choices = room_choice, 
  selected = "Entire home/apt")



```

Column {data-width=650}
-----------------------------------------------------------------------

### Chart A

```{r}
renderPlotly({ 
  
  nyc_airbnb %>%
    filter(borough == input[["borough_choice"]],
           room_type == input[["room_choice"]],
           price %in% input$price_choice[1]:input$price_choice[2]) %>% 
  mutate(text_label = str_c("Price: $", price, '\nRating: ', stars)) %>% 
  plot_ly(
    x = ~lat, y = ~long, type = "scatter", mode = "markers",
    alpha = 0.5, color = ~price, text = ~text_label)
})
  
  

```

Column {data-width=350}
-----------------------------------------------------------------------

### Chart B

```{r}
renderPrint({ 
  input[["price_choice"]]
})
```

### Chart C

```{r}
renderPrint({ 
  input[["room_choice"]]
})
```

